[package]
name = "intel_pt_libpng"
authors = ["Marco Cavenati <cavenatimarco@gmail.com>"]
edition = "2021"

[features]
tui = ["libafl/tui_monitor"]

[dependencies]
libafl = { path = "../../../crates/libafl/", features = ["intel_pt"] }
libafl_bolts = { path = "../../../crates/libafl_bolts" }
proc-maps = "0.4.0"
env_logger = "0.11.10"

[build-dependencies]
bindgen = "0.72.1"
cc = "1.2.60"
cmake = "0.1.58"
